dataset: configs/yolo-data.yaml

training:
  epochs: 30
  batch_size: 4
  image_size: 512
  weight_decay: 0.1

model:
  weights: yolo12n.pt
  device: null

output:
  project: experiments
  name: yolo12n-results

augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
